import { ChatMessage, Contact } from "../types/chat";

export const APP_ICON = require("../assets/images/icon.png");
export const REACT_LOGO = require("../assets/images/react-logo.png");

export const CONTACTS: Contact[] = [
  {
    id: "ava",
    name: "林語安",
    handle: "@語安",
    accentColor: "#0a84ff",
    isOnline: true,
  },
  {
    id: "ethan",
    name: "吳奕辰",
    handle: "@奕辰",
    accentColor: "#13c76a",
    isOnline: true,
  },
  {
    id: "mia",
    name: "陳米雅",
    handle: "@米雅",
    accentColor: "#ff6a3d",
    isOnline: false,
  },
  {
    id: "noah",
    name: "黃諾亞",
    handle: "@諾亞",
    accentColor: "#9a5bff",
    isOnline: true,
  },
  {
    id: "zoe",
    name: "李若依",
    handle: "@若依",
    accentColor: "#f23f7f",
    isOnline: false,
  },
];

type ScriptLine = {
  from: "me" | "them";
  text: string;
};

const scripts: Record<string, ScriptLine[]> = {
  ava: [
    { from: "them", text: "早安，你有看設計交接檔了嗎？" },
    { from: "me", text: "剛打開，現在間距看起來更乾淨了。" },
    { from: "them", text: "不錯，訊息卡可以維持像 Messenger 那種圓角嗎？" },
    { from: "me", text: "可以，我會再把圓角加大一點。" },
    { from: "them", text: "很好，搜尋列對比也要再強一點。" },
    { from: "me", text: "我會把邊框和背景再加深。" },
    { from: "them", text: "完美，對了中午 12:30 一起吃嗎？" },
    { from: "me", text: "可以，我沒問題。" },
    { from: "them", text: "我傳了一張截圖給你對比風格。" },
    { from: "me", text: "已經很接近了，只要把 icon 節奏再調好。" },
    { from: "them", text: "還有對話列表上方留白可以再縮小。" },
    { from: "me", text: "已調整，現在密度更像 Messenger。" },
    { from: "them", text: "太好了，未讀點可以維持在右側嗎？" },
    { from: "me", text: "可以，未讀點會固定在尾端。" },
    { from: "them", text: "今晚我會在 Android 和 iOS 都測一次。" },
    { from: "me", text: "好，有任何互動不順再告訴我。" },
    { from: "them", text: "沒問題，這個 App 越來越完整了。" },
    { from: "me", text: "謝謝你。" },
    { from: "them", text: "輸入區可以加快速選照片嗎？" },
    { from: "them", text: "很急可以趕快做嗎？" },
    { from: "me", text: "已經排進去，選圖按鈕正在做。" },
    { from: "them", text: "很好，完成就可以上線展示。" },
    { from: "me", text: "收到，馬上處理。" },
  ],
  ethan: [
    { from: "them", text: "這週五要不要來遊戲夜？" },
    { from: "me", text: "好啊，我參加，幾點開始？" },
    { from: "them", text: "晚上八點，老地方。" },
    { from: "me", text: "可以，我會帶點零食。" },
    { from: "them", text: "那記得帶辣味洋芋片。" },
    { from: "me", text: "收到。" },
    { from: "them", text: "另外我試了你的新版本，滑起來超順。" },
    { from: "me", text: "謝啦，我有調整列表滾動的細節。" },
    { from: "them", text: "之後可以做置頂對話嗎？" },
    { from: "me", text: "可以，但我先把基礎相似度做完。" },
    { from: "them", text: "合理，輸入區先維持精簡一排。" },
    { from: "me", text: "對，單排輸入加 icon 操作。" },
    { from: "them", text: "這就很像 Messenger 了。" },
    { from: "me", text: "我也把自己訊息泡泡藍色調接近原版。" },
    { from: "me", text: "已讀狀態要不要一起做假資料？" },
    { from: "them", text: "先不用，這版先專注主流程。" },
    { from: "me", text: "了解。" },
    { from: "them", text: "讚。" },
    { from: "them", text: "下班後我再給你一輪回饋。" },
    { from: "me", text: "好，等你。" },
    { from: "them", text: "那週五見。" },
    { from: "me", text: "週五見。" },
  ],
  mia: [
    { from: "them", text: "我們的最終色盤確定了嗎？" },
    { from: "me", text: "主色是 #0a84ff，中性色用 slate 系列。" },
    { from: "them", text: "字體設定可以再分享一次嗎？" },
    { from: "me", text: "用系統字體堆疊，確保原生一致性。" },
    { from: "them", text: "很好，頁面載入有做動畫嗎？" },
    { from: "me", text: "只有列表卡片的淡入，不做過重特效。" },
    { from: "them", text: "聽起來很乾淨。" },
    { from: "me", text: "對，主要是兼顧效能。" },
    { from: "them", text: "資料是完全本地嗎？" },
    { from: "me", text: "是，所有訊息都存在記憶體。" },
    { from: "them", text: "也沒有串任何後端？" },
    { from: "me", text: "完全沒有。" },
    { from: "them", text: "那很適合 demo 模式。" },
    { from: "me", text: "沒錯。" },
    { from: "them", text: "使用者可以從手機相簿選照片嗎？" },
    { from: "me", text: "可以，已接上 Expo Image Picker。" },
    { from: "them", text: "太好了，這是必備需求。" },
    { from: "me", text: "我已經把它接到輸入區按鈕了。" },
    { from: "them", text: "那這版其實差不多完成。" },
    { from: "me", text: "我再把間距細修一下就能交付。" },
    { from: "them", text: "辛苦了。" },
    { from: "me", text: "不會，應該的。" },
  ],
  noah: [
    { from: "them", text: "可以幫我看一下這個 PR 嗎？" },
    { from: "me", text: "可以，給我十分鐘。" },
    { from: "them", text: "主要改了聊天室卡片的渲染。" },
    { from: "me", text: "我正在看邊界情況。" },
    { from: "them", text: "麻煩特別看長訊息換行。" },
    { from: "me", text: "看起來安全，窄螢幕也沒有溢出。" },
    { from: "them", text: "太好了。" },
    { from: "me", text: "我有留一些命名和樣式註解。" },
    { from: "them", text: "好，我等等補上。" },
    { from: "me", text: "可以。" },
    { from: "them", text: "對了，你聊天室頂欄真的很像 Messenger。" },
    { from: "me", text: "這就是這版的目標。" },
    { from: "them", text: "頭像上能加小小在線點嗎？" },
    { from: "me", text: "已經做了，列表和聊天室都有。" },
    { from: "them", text: "細節很棒。" },
    { from: "me", text: "icon 按鈕尺寸我也統一了。" },
    { from: "them", text: "很好，點擊更順手。" },
    { from: "me", text: "沒錯。" },
    { from: "them", text: "那我等你同意後就 merge。" },
    { from: "me", text: "我這邊已同意。" },
    { from: "them", text: "感謝！" },
    { from: "me", text: "不客氣。" },
  ],
  zoe: [
    { from: "them", text: "週末旅行的照片都整理好了。" },
    { from: "me", text: "快傳幾張精華給我看！" },
    { from: "them", text: "我要先從相簿選才能傳。" },
    { from: "me", text: "選圖按鈕現在應該能用了。" },
    { from: "them", text: "太好了，我等等就測。" },
    { from: "me", text: "直式和橫式都可以試看看。" },
    { from: "them", text: "好喔，那有支援圖片說明嗎？" },
    { from: "me", text: "這版先不做，只支援純圖片。" },
    { from: "them", text: "可以，這樣就夠 demo 了。" },
    { from: "me", text: "我也調整了泡泡最大寬度。" },
    { from: "them", text: "可讀性真的好很多。" },
    { from: "me", text: "太好了。" },
    { from: "them", text: "我也能看到原本的長訊息嗎？" },
    { from: "me", text: "可以，每位聯絡人都有預設長對話。" },
    { from: "them", text: "那就很適合展示滾動效果。" },
    { from: "me", text: "沒錯，這就是用途。" },
    { from: "them", text: "我很喜歡這個風格。" },
    { from: "me", text: "你喜歡就好。" },
    { from: "them", text: "最終版好了再通知我。" },
    { from: "me", text: "今晚完成我就通知你。" },
    { from: "them", text: "好，等你消息。" },
    { from: "me", text: "晚點聊。" },
  ],
};

function buildConversation(
  contactId: string,
  lines: ScriptLine[],
  startMinutesAgo: number,
): ChatMessage[] {
  return lines.map((line, index) => ({
    id: `${contactId}-${index + 1}`,
    contactId,
    senderId: line.from === "me" ? "me" : contactId,
    text: line.text,
    createdAt: Date.now() - (startMinutesAgo - index * 3) * 60 * 1000,
  }));
}

export const INITIAL_MESSAGES: Record<string, ChatMessage[]> = {
  ava: buildConversation("ava", scripts.ava, 180),
  ethan: buildConversation("ethan", scripts.ethan, 260),
  mia: buildConversation("mia", scripts.mia, 340),
  noah: buildConversation("noah", scripts.noah, 420),
  zoe: buildConversation("zoe", scripts.zoe, 500),
};
